name: Archive the latest modules

on: workflow_dispatch
# on: 
  # schedule:
  #   - cron: '0 0 * * * '

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - name: Run a script to download all information for modules
        run: node ./.github/workflows/archive-modules.js
      - name: Run a script to download all information for collections
        run: node ./.github/workflows/archive-collections.js
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          committer_name: ResearchEquals Archiver
          message: 'Nightly archive update'
  build_deploy:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: archive.researchequals.com